# Generated by Django 5.2.6 on 2025-10-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='constellations.actor', verbose_name='Актёры'),
        ),
    ]
